### ISSUE TITLE
Garbled characters when exporting to PNG format

### ISSUE THREAD

**Issue by Hongqing-Hu** [altair-viz/altair_saver#110]
Chinese fonts are displayed normally in HTML format. Garbled characters when exporting to PNG format.

`import pandas as pd
import altair as alt
from altair_saver import save

df = pd.DataFrame({"x":[0.5,1,2], 
                   "y" : [0.5,1,2], 
                   "text": ["你好", "中国", "明天"]})

pic = alt.Chart(df).mark_text().encode(
    x = "x",
    y=  'y',
    text ='text'
)
save(pic, "text.png")`

**Comment by joelostblom** [comment]
Since Altair 5.2, the functionality of Altair Saver is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package. Most of the functionality has been available since 5.0, and [the main addition in 5.2 was PDF export](https://github.com/altair-viz/altair/pull/3244). See [the docs on how to save charts](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format) for more details

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for saving charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
