### ISSUE TITLE
save chart using method "node" not running anymore with npm@9

### ISSUE THREAD

**Issue by mhombrecher** [altair-viz/altair_saver#113]
Saving a chart as .png causes an "CalledProcessError" error when using method "node" and npm version is node@9

Reason is that npm has removed command: "npm bin" since version 9 which is used in _node.py (npm_bin)

**Comment by mhombrecher** [comment]
Sorrry,  meant of course npm@9

**Comment by cotsuka** [comment]
Confirming rolling back to npm < 9 seems to work.

**Comment by aravindvnair99** [comment]
Hi team!

Any updates on this issue?

**Comment by jschaef** [comment]
> 
This
https://github.com/anmol098/waka-readme-stats/issues/337#issuecomment-1396737897

is working for me with `npm --version 9.3.1`

**Comment by joelostblom** [comment]
Since Altair 5.2, the functionality of Altair Saver is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package. Most of the functionality has been available since 5.0, and [the main addition in 5.2 was PDF export](https://github.com/altair-viz/altair/pull/3244). See [the docs on how to save charts](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format) for more details

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for saving charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
