### ISSUE TITLE
scale_factor in altair_saver?

### ISSUE THREAD

**Issue by danhamill** [altair-viz/altair_saver#39]
I have been using `altair_saver` as an alternative to `chart.save` because I keep running into headless chrome timeouts when I am producing lots of charts.  However, the plots are at a much lower resolution and have a grainy appearance using `altair_saver.save` compared to  `chart.save` method in the `altair` library.

Is there a way to control the figure resolution using `altair_saver`?

**Comment by jakevdp** [comment]
If you're using the selenium-based saver, you can pass it directly to the save command:
```python
altair_saver.save(chart, 'chart.png', method='selenium',  scale_factor=2)
```
If you're using the node-based saver, setting scale factor is not possible because there is no way to specify it in the underlying npm commands.

Note that in future releases of altair_saver (and currently in master), the ``scale_factor`` argument will be deprecated in favor of using altair's rendering options directly, i.e.
```python
alt.renderers.set_embed_options(scaleFactor=2)
```
