### ISSUE TITLE
Support native PDF LaTeX export

### ISSUE THREAD

**Issue by jgonsior** [altair-viz/altair_saver#63]
Currently I use the ```inkscape -D -z --file input.svg --export-pdf output.pdf_tex --export-latex``` to create a PDF file that can be imported into LaTeX and uses the fonts etc. from LaTeX. But I have to manually escape f.e. the percentage signs from the axis or fiddle around quite a lot to make the paddings etc. work. Therefore I'd like to know, if a native latex PDF LaTeX export is on the table for the future.

**Comment by taralloc** [comment]
As a very basic workaround for the font, you can install the Computer Modern font from [here](https://www.fontsquirrel.com/fonts/computer-modern) and then use it in your Altair code with something like `labelFont='CMU Serif'`.

**Comment by AirManH** [comment]
AFAIK, `matplotlib` support [exporting plots to latex](https://matplotlib.org/tutorials/text/pgf.html)  like:

``` latex
plt.savefig('figure.pdf', backend='pgf')
```

I often have to insert plots in latex, and if you could provide similar feature, this will become an advantage of `alrair`. :)

**Comment by jakevdp** [comment]
If that feature is important to you, I’d suggest sticking with matplotlib.

**Comment by joelostblom** [comment]
Since Altair 5.2, the functionality of Altair Saver is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package. Most of the functionality has been available since 5.0, and [the main addition in 5.2 was PDF export](https://github.com/altair-viz/altair/pull/3244). See [the docs on how to save charts](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format) for more details.

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for saving charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
