### ISSUE TITLE
Saving to svg using Node on Windows

### ISSUE THREAD

**Issue by sjorspeterse** [altair-viz/altair_saver#70]
Hi, thank you for your amazing work!

I tried generating svg images using NodeJS, but got an `ValueError: Unsupported format: 'svg'`.
After removing a newline character from the npm_bin path, it worked.
In savers/_node.py, I changed 
`return check_output_with_stderr(cmd).decode()` 
for 
`return check_output_with_stderr(cmd).decode().rstrip('\n')`

I don't really understand where that newline came from, but I'm using Windows 10.
Hope this helps!

**Comment by sjorspeterse** [comment]
Oops, just saw that this is already fixed!

**Comment by sjorspeterse** [comment]
I can't seem to update from version 0.1.0 to 0.5.0 because that requires vega-cli and vega-lite-cli, and those are not available for Windows on [Anaconda](https://anaconda.org/conda-forge/vega-cli). Does that mean you're no longer supporting Windows? I'm sorry if this is a trivial question.

**Comment by jamesmyatt** [comment]
I'm also on Windows and stuck on 0.1.0 because of the `vega-cli` and `vega-lite-cli` dependencies. And the selenium version is not working for me, despite the `python-chromedriver-binary` being available.

**Comment by jakevdp** [comment]
For selenium, the chromedriver binary is not enough. You also need a compatible version of Google Chrome.

**Comment by jamesmyatt** [comment]
0.5.0 is available on conda-forge for win64 now, since @xhochy updated the vega-cli and vega-lite-cli dependencies for Windows.

**Comment by joelostblom** [comment]
Since Altair 5.2, the functionality of Altair Saver is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package. Most of the functionality has been available since 5.0, and [the main addition in 5.2 was PDF export](https://github.com/altair-viz/altair/pull/3244). See [the docs on how to save charts](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format) for more details.

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for saving charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
