### ISSUE TITLE
Selenium/Geckodriver consumes all memory

### ISSUE THREAD

**Issue by jploudre** [altair-viz/altair_saver#73]
Mostly wanted to say Thanks! I'm not sure I can troubleshoot it. 

Altair_saver is much faster (~6x for me) than doing geckodriver on charts one at a time. 

On Linux with Firefox, altair_saver with selenium/geckodriver steadily consumes memory while running through iterations (done with multiprocessing) and crashes. Switching to node with method eliminates memory consumption.

**Comment by jakevdp** [comment]
Thanks for the report – there's probably some selenium cleanup or garbage collecting that is missing from the package.

**Comment by joelostblom** [comment]
Since Altair 5.2, the functionality of Altair Saver is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package. Most of the functionality has been available since 5.0, and [the main addition in 5.2 was PDF export](https://github.com/altair-viz/altair/pull/3244). See [the docs on how to save charts](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format) for more details.

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for saving charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
