### ISSUE TITLE
JupyterLab saving plots

### ISSUE THREAD

**Issue by teucer** [altair-viz/altair_saver#74]
It seems that altair is able to save plots out of the box using actions. Could this be leveraged to save the plots to png/svg programmatically?

**Comment by jakevdp** [comment]
There is information on programmatically saving charts here: https://altair-viz.github.io/user_guide/saving_charts.html

If by leveraging actions, you mean programmatically clicking the actions buttons in Jupyter via javascript injected into the notebook, I have not tried that but it should be possible in principle.

**Comment by teucer** [comment]
I have seen the link and understand why it is required. 

However, the need to install many tools to "just" save the chart as a png is probably not very user-friendly. Having it integrated in the main package would be more productive in my opinion.

**Comment by jakevdp** [comment]
> Having it integrated in the main package would be more productive in my opinion.

That would be great, but there's not really any way to do that. Rendering charts currently requires a javascript environment: you can either use a browser to render the charts manually (as in Jupyter/JupyterLab) or via extra dependencies (either nodejs-based tools, or selenium working with an appropriate headless browser). I don't know of any way around that.

**Comment by teucer** [comment]
What about creating platform specific executables using e.g. [pkg](https://github.com/vercel/pkg)?

**Comment by joelostblom** [comment]
Since Altair 5.2, the functionality of Altair Saver is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package. Most of the functionality has been available since 5.0, and [the main addition in 5.2 was PDF export](https://github.com/altair-viz/altair/pull/3244). See [the docs on how to save charts](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format) for more details.

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for saving charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
