### ISSUE TITLE
Saving figure with interactive elements

### ISSUE THREAD

**Issue by robna** [altair-viz/altair_saver#82]
Is it possible to export interactive features?
For testing I made a plot with tool tips on hover and saved to pdf and svg (via nodejs). The figure is saved without problems, but the tool tip functionality is lost.

**Comment by jakevdp** [comment]
You can save a figure to HTML and preserve interactive elements. I'm not aware of any way to create an interactive pdf or svg.

**Comment by robna** [comment]
About pdf I also don't know if it would be feasible at all. Interactive svg however should be possible, as there are projects like @petercollingridge/code-for-blog or @sozi-projects/Sozi

And how exactly would I get interactivity in an html output? What I tried sofar is `alt.Chart.show(name-of-my-chart)` which opens the chart in a new browser window (outside of jupyter lab), but without interactivity.

**Comment by robna** [comment]
sorry my mistake... `alt.Chart.show(name-of-my-chart)`  wouldn't even be using altair_saver, but the main altair library, right?
I tried now:
`from altair_saver import save`
`save(qhm,'quant_HM.html')`
This exports a html file with interactivity preserved.

Do you know by any chance if someone has tried to make export of altair charts with interactivity work in formats such as svg or pdf?

**Comment by jakevdp** [comment]
No, I don't believe pdf files or svg files support interactivity, so there is no way to make Altair exports to those filetypes include interactivity. The only way to export interactive Altair charts is to save them to html, for example with `chart.save('filename.html')` and then view it in a web browser, or to save them to JSON with `chart.save(filename.json)` and then load it in javascript with something like vega-embed.

**Comment by joelostblom** [comment]
Since Altair 5.2, the functionality of Altair Saver is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package. Most of the functionality has been available since 5.0, and [the main addition in 5.2 was PDF export](https://github.com/altair-viz/altair/pull/3244). See [the docs on how to save charts](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format) for more details

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for saving charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
