### ISSUE TITLE
Add a saver based on Kaleido

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair_saver#85]
This would make it easier to distribute and install the required dependencies: https://github.com/plotly/Kaleido

**Comment by bodacious-bill** [comment]
Seconding this. I recently stumbled upon Altair, and I love the speed and flexibility it offers.

However, my workplace is having problems with installing the odd dependencies of altair_saver, and making sure they work with our Jupyterlab implementation. Meanwhile, Kaleido is a simple installation and works fine with plotly.

I still prefer Altair to plotly, but I'm afraid I'll have to use plotly/Kaleido instead since I can't save charts to images with Altair currently.

**Comment by jakevdp** [comment]
Awesome - is this something you'd be willing to work on?

**Comment by bodacious-bill** [comment]
Well, I would, but I don't really have a coding background. I'm an engineer and mainly code in python for data analysis. I don't know C++ or javascript.

Would I be able to contribute? I'd be happy to if so, but it seems out of my wheelhouse.

**Comment by joelostblom** [comment]
Since Altair 5.2, the functionality of Altair Saver is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package. Most of the functionality has been available since 5.0, and [the main addition in 5.2 was PDF export](https://github.com/altair-viz/altair/pull/3244). See [the docs on how to save charts](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format) for more details

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for saving charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
