### ISSUE TITLE
charts saved in png format are pixelated, even when increasing `scaling_factor`

### ISSUE THREAD

**Issue by mayorana** [altair-viz/altair_saver#94]
Hi, recently I've been experiencing an issue with altair saver, even if I increase the parameter `scaling_factor` to 4.0, the exported .png is pixelated. I could reproduce the same issue when running the example notebook on [Colab](https://github.com/altair-viz/altair_saver/blob/master/AltairSaver.ipynb). I suspect it might be connected to the latest release of [vega-lite-cli](https://anaconda.org/conda-forge/vega-lite-cli) but I have no proof.

Can you please help me with this problem?

**Comment by joelostblom** [comment]
Since Altair 5.2, the functionality of Altair Saver is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package. Most of the functionality has been available since 5.0, and [the main addition in 5.2 was PDF export](https://github.com/altair-viz/altair/pull/3244). See [the docs on how to save charts](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format) for more details

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for saving charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
