### ISSUE TITLE
Let save() take Pathlib path

### ISSUE THREAD

**Issue by RoyalTS** [altair-viz/altair_saver#96]
Seems like at the present one has to cast to `str` before passing such a `path` to `save()` as per https://github.com/altair-viz/altair_saver/blob/dbbc093203a2456e294ae4f296477a7ef252a339/altair_saver/_core.py#L76

**Comment by joelostblom** [comment]
Since Altair 5.2, the functionality of Altair Saver is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package. Most of the functionality has been available since 5.0, and [the main addition in 5.2 was PDF export](https://github.com/altair-viz/altair/pull/3244). See [the docs on how to save charts](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format) for more details

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for saving charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
